name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm run build --if-present
    - name: Deploy to Server
      uses: wlixcc/SFTP-Deploy-Action@v1.0
      with:
          ssh_private_key: ${{ secrets.TENXUNYUN_SSH_PRIVATE_KEY }}
          # ARGS: "-rltgoDzvO --delete"
          local_path: "build/"
          server: ${{ secrets.HOST }}
          username: "root"
          remote_path: "/root/www/build"
          # EXCLUDE: "/dist/, /node_modules/"
